# Autogenerated by /__w/lowrisc-toolchains/lowrisc-toolchains/generate-gcc-cmake-toolchain.sh on Tue Feb  6 17:56:41 UTC 2024
# Problems? Bug reporting instructions in /tools/riscv/buildinfo
#
# If you have relocated this toolchain, pass '-DLOWRISC_TOOLCHAIN=' to point to
# the new location of the toolchain when invoking CMake, before the -C argument
# which points to this file.

if(NOT LOWRISC_TOOLCHAIN)
  set(LOWRISC_TOOLCHAIN "/tools/riscv")
endif()

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR riscv64)



set(CMAKE_C_COMPILER "${LOWRISC_TOOLCHAIN}/bin/riscv64-unknown-elf-gcc" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_TARGET "riscv64-unknown-elf" CACHE STRING "" FORCE)
set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN "${LOWRISC_TOOLCHAIN}" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "" CACHE STRING "" FORCE)

set(CMAKE_CXX_COMPILER "${LOWRISC_TOOLCHAIN}/bin/riscv64-unknown-elf-g++" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_TARGET "riscv64-unknown-elf" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN "${LOWRISC_TOOLCHAIN}" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "" CACHE STRING "" FORCE)

set(CMAKE_ASM_COMPILER "${LOWRISC_TOOLCHAIN}/bin/riscv64-unknown-elf-as" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_TARGET "riscv64-unknown-elf" CACHE STRING "" FORCE)
set(CMAKE_ASM_COMPILER_EXTERNAL_TOOLCHAIN "${LOWRISC_TOOLCHAIN}" CACHE STRING "" FORCE)
set(CMAKE_ASM_FLAGS "" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
